PandaApp/PandaApp/Models/Request.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PandaApp.Models
{
    public class Request
    {
        public int ID { get; set; }
        
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }
        public string Author { get; set; }
        public int MediaID { get; set; }

        [Required]
        [Display(Name = "Language")]
        public string Language { get; set; }

        [Display(Name = "YouTube/Vimeo")]
        public string ExternalVideoLink { get; set; }
        public int Upvotes { get; set; }

        [Display(Name = "Added")]
        public DateTime DateCreated { get; set; }

        public bool UpvotedByUser { get; set; }
        
        [Display(Name = "Subtitle link")]
        public string SubtitleLink { get; set; }
        
        public Request()
		{
			DateCreated = DateTime.Now;
		}
    }
}

PandaApp/PandaApp/Controllers/RequestController.cs
using PandaApp.Models;
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace PandaApp.Controllers
{
    public class RequestController : Controller
    {
        PandaRepo db = new PandaRepo();

        public ActionResult Index(int? page)
        {
            // Gets username of logged in user.
            string username = User.Identity.Name;

            IEnumerable<Request> requests = (from item in db.GetAllRequests()
                                             orderby item.DateCreated descending
                                             select item);

            // By default we start at page one
            if (!page.HasValue)
            {
                page = 1;
            }

            int pageSize = 15;
            int pageNumber = (page ?? 1);

            if (username.Length != 0)
            {
                foreach (Request req in requests)
                {
                    // If you have upvoted this request it will return true, false otherwise.
                    req.UpvotedByUser = db.GetReqUpBool(req.ID, db.GetUserByName(username).ID);
                }
            }

            // Gets language dropdown
            ViewBag.Languages = db.GetLanguageListItems();
            return View(requests.ToPagedList(pageNumber, pageSize));
        }        

        public ActionResult RequestSearch(int? page, string title, string language)
        {
            IEnumerable<Request> req;

            if (language.Length == 0)
            {
                // Gets all requests sorted by upvote count
                req = (from item in db.GetAllRequests()
                       where item.Title.ToLower().Contains(title.ToLower())
                       orderby item.Upvotes descending
                       select item);
            }
            else
            {
                // Gets all requests with the specified language
                // sorts the results by upvotes
                req = (from item in db.GetAllRequests()
                       where (item.Title.ToLower().Contains(title.ToLower()) &&
                       (item.Language == language))
                       orderby item.Upvotes descending
                       select item);
            }

            // This is for the upvote system
            string username = User.Identity.Name;
            if (username.Length != 0)
            {
                foreach (Request item in req)
                {
                    // If you have upvoted this request it will return true, false otherwise.
                    item.UpvotedByUser = db.GetReqUpBool(item.ID, db.GetUserByName(username).ID);
                }
            }

            // This is the for the paging
            if (!page.HasValue)
            {
                page = 1;
            }

            int pageSize = 15;
            int pageNumber = (page ?? 1);

            // Gets language dropdown
            ViewBag.Languages = db.GetLanguageListItems();

            return View(req.ToPagedList(pageNumber, pageSize));
        }
        //Returns the Create view for a request
        [HttpGet]
        public ActionResult Create()
        {
            // Gets language dropdown
            ViewBag.Languages = db.GetLanguageListItems();
            return View(new Request());
        }

        //Submits a request to the database, 
        //and returns the user to the Index
        [HttpPost]
        public ActionResult Create(Request item)
        {
            if (ModelState.IsValid)
            {
                if (User.Identity.Name.Length == 0)
                {
                    item.Author = "Guest";
                }
                else
                {
                    item.Author = User.Identity.Name;
                }
                db.AddRequest(item);

                return RedirectToAction("Index");
            }

            // Gets language dropdown
            ViewBag.Languages = db.GetLanguageListItems();
            return View();
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            ReqUp r = new ReqUp();

            // Gets request with 'id'
            r.request = db.GetRequestById(id);
            // Gets account details for the logged in user
            Account acc = db.GetUserByName(User.Identity.Name);

            // If the user exists
            if (db.GetUserByName(User.Identity.Name) != null)
            {
                // Returns true if the user has upvoted the request
                r.upvoted = db.GetReqUpBool(id, acc.ID);
            }
            else
            {
                r.upvoted = false;
            }
            
            if (r != null)
            {
                return View(r);
            }
            return View("NotFound");
        }

        [Authorize]
        [HttpPost]
        public void Upvote(int id)
        {
            PandaBase panda = new PandaBase();
            
            //Tékkað á því hvort það sé til Upvote með þessari ákveðnu beiðni og notanda. 
            //Ef 'true' þá er það ekki til og haldið er áfram.
            if(db.GetReqUpBool(id, db.GetUserByName(User.Identity.Name).ID))
            {
                // Find request with 'id' and raises upvote with 1
                Request req = panda.Requests.Single(re => re.ID == id);
                req.Upvotes++;

                // Adds a line to Upvoters table with the users ID and request ID
                Upvoter upvoter = new Upvoter() { RequestID = id, UserID = db.GetUserByName(User.Identity.Name).ID };
                panda.Upvoters.Add(upvoter);

                panda.SaveChanges();
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult FillRequest(int requestID, string subtitleLink)
        {
            db.FillReq(requestID, subtitleLink);

            return RedirectToAction("Details/" + requestID);
        }
	}
}

PandaApp/PandaApp/Views/Request/Create.cshtml
@model PandaApp.Models.Request

@{
    ViewBag.Title = "Create";
}

<h2>Create Request</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Language", (IEnumerable<SelectListItem>)ViewBag.Languages, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Language)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExternalVideoLink, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ExternalVideoLink, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExternalVideoLink)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PandaApp/PandaApp/Views/Request/Details.cshtml
@model PandaApp.Models.ReqUp

@{
    ViewBag.Title = "Details";
}

<h2>Request details</h2>

<div>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.request.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.request.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.request.Author)
        </dt>

        <dd>
            @if (Model.request.Author == "Guest")
            {
                @Model.request.Author
            }
            else
            {
                @Html.ActionLink(Model.request.Author, "ViewUser", "Account", new { username = Model.request.Author }, null)
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.request.Language)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.request.Language)
        </dd>
        
        @* Hides video link if its empty *@
        @if (Model.request.ExternalVideoLink != null)
        {
        <dt>
            @Html.DisplayNameFor(model => model.request.ExternalVideoLink)
        </dt>

        <dd>
            <a href="@Model.request.ExternalVideoLink">@Model.request.ExternalVideoLink</a>
        </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.request.Upvotes)
        </dt>

        <dd class="d_upvotes">
            @Html.DisplayFor(model => model.request.Upvotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.request.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.request.DateCreated)
        </dd>

        <dt>
            Filled
        </dt>

        @if (Model.request.SubtitleLink != null)
        {
        <dd>
            <a href="@Model.request.SubtitleLink">Yes</a>
        </dd>
        }
        else
        {
        <dd>
            <p>No</p>
        </dd>
        }

    </dl>
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-4">
        @if (Model.request.SubtitleLink == null)
        {
            using (Html.BeginForm("FillRequest", "Request", FormMethod.Post))
            {
                <label class="col-md-2 control-label">Fill request</label>
                <input type="hidden" name="requestID" value="@Model.request.ID" />
                <input type="text" name="subtitleLink" class="form-control" placeholder="Enter subtitle link" />
                <input type="submit" class="btn btn-default" value="Fill">
            }
        }
    </div>
</div>

<table>
    <tbody>
        <tr>
            <td id="margin_1">
                <p id="return_link_1">
                    @Html.ActionLink("Back to List", "Index")
                </p>
            </td>
            @if (Model.upvoted)
            {
                <td>
                    <div class="row text-center">
                        @using (Html.BeginForm("Upvote", "Request", FormMethod.Post, new { @class = "upvote" }))
                        {
                            <input type="hidden" name="id" value="@Model.request.ID" />
                            <input type="submit" class="btn btn" value="Upvote">
                        }
                    </div>
                </td>
            }
        </tr>
    </tbody>
</table>

<script src="~/Scripts/UpvoteScript.js"></script>

PandaApp/PandaApp/Views/Request/Index.cshtml
@model PagedList.IPagedList<PandaApp.Models.Request>

@{
    ViewBag.Title = "Requests";
}

<!-- Search begins -->
<div class="row text-center">
    @using (Html.BeginForm("RequestSearch", "Request"))
    {
        <input type="text" class="form-control" id="input" name="title" size="21" maxlength="120" placeholder="Request search">
        @Html.DropDownList("Language", (IEnumerable<SelectListItem>)ViewBag.Languages, new { @class = "form-control" })
        <input type="submit" class="btn btn-default" value="Search">
    }
</div>
<!-- Search ends -->

<h2>View Requests</h2>
<hr />

@Html.ActionLink("Create Request", "Create", null, new { @class = "btn btn-default" })

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Language)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Upvotes)
            </th>    
            <th>
                Filled
            </th>        
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <!-- So the title links to its profile -->
                    @Html.ActionLink(item.Title, "Details", "Request",new { id = item.ID }, null)
                </td>
                <td>
                    @item.Language
                </td>
                <td>
                    @if (@item.Author == "Guest")
                    {
                        @item.Author
                    }
                    else
                    {
                        @Html.ActionLink(item.Author, "ViewUser", "Account", new { username = item.Author }, null)
                    }
                </td>
                <td>
                    @item.DateCreated
                </td>
                <td>
                    @if (item.UpvotedByUser)
                    {
                        using (Html.BeginForm("Upvote", "Request", FormMethod.Post, new { @class = "upvote" }))
                        {
                            <input type="hidden" name="id" value="@item.ID" />
                            <button type="submit" class="btn btn-mini" value="+">
                                @item.Upvotes
                                <span class="glyphicon glyphicon-arrow-up"></span>
                            </button>
                        }
                    }
                    else
                    {
                        <button type="button" class="btn btn-mini" value="">
                            @item.Upvotes
                        </button>
                    }
                </td>
                <td>
                    @if (item.SubtitleLink.IsEmpty())
                    {
                        <p>No</p>
                    }
                    else
                    {
                        <a href="@item.SubtitleLink">Yes</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="page-nav">
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { page = 1 })
        @Html.Raw(" ")
        @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1 })
    }
    else
    {
        @:&lt;&lt;
        @Html.Raw(" ")
        @:&lt; Prev
    }

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)

    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1 })
        @Html.Raw(" ")
        @Html.ActionLink(">>", "Index", new { page = Model.PageCount })
    }
    else
    {
        @:Next &gt;
        @Html.Raw(" ")
        @:&gt;&gt;
    }
</div>

<script src="~/Scripts/UpvoteScript.js"></script>

PandaApp/PandaApp/Views/Request/RequestSearch.cshtml
@model PagedList.IPagedList<PandaApp.Models.Request>

@{
    ViewBag.Title = "Search results";
}

<!-- Search begins -->
<div class="row text-center">
    @using (Html.BeginForm("RequestSearch", "Request"))
    {
        <input type="text" class="form-control" id="input" name="title" size="21" maxlength="120" placeholder="Request search">
        @Html.DropDownList("Language", (IEnumerable<SelectListItem>)ViewBag.Languages, new { @class = "form-control" })
        <input type="submit" class="btn btn-default" value="Search">
    }
</div>
<!-- Search ends -->

<h2>Search results</h2>
<hr />

@Html.ActionLink("Create Request", "Create", null, new { @class = "btn btn-default" })

@if (!Model.Any())
{
    <p>No requests were found.</p>
}
else
{
    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Language)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Upvotes)
            </th>    
            <th>
                Filled
            </th>        
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <!-- So the title links to its profile -->
                    @Html.ActionLink(item.Title, "Details", "Request",new { id = item.ID }, null)
                </td>
                <td>
                    @item.Language
                </td>
                <td>
                    @if (@item.Author == "Guest")
                    {
                        @item.Author
                    }
                    else
                    {
                        @Html.ActionLink(item.Author, "ViewUser", "Account", new { username = item.Author }, null)
                    }
                </td>
                <td>
                    @item.DateCreated
                </td>
                <td>
                    @if (item.UpvotedByUser)
                    {
                        using (Html.BeginForm("Upvote", "Request", FormMethod.Post, new { @class = "upvote" }))
                        {
                            <input type="hidden" name="id" value="@item.ID" />
                            <button type="submit" class="btn btn-mini" value="+">
                                @item.Upvotes
                                <span class="glyphicon glyphicon-arrow-up"></span>
                            </button>
                        }
                    }
                    else
                    {
                        <button type="button" class="btn btn-mini" value="">
                            @item.Upvotes
                        </button>
                    }
                </td>
                <td>
                    @if (item.SubtitleLink.IsEmpty())
                    {
                        <p>No</p>
                    }
                    else {
                        <a href="@item.SubtitleLink">Yes</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
}

<div class="page-nav">
    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "Index", new { page = 1 })
        @Html.Raw(" ")
        @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1 })
    }
    else
    {
        @:&lt;&lt;
        @Html.Raw(" ")
        @:&lt; Prev
    }

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)

    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "RequestSearch", new { page = Model.PageNumber + 1 })
        @Html.Raw(" ")
        @Html.ActionLink(">>", "RequestSearch", new { page = Model.PageCount })
    }
    else
    {
        @:Next &gt;
        @Html.Raw(" ")
        @:&gt;&gt;
    }
</div>

<script src="~/Scripts/UpvoteScript.js"></script>

PandaApp/PandaApp/Views/Request/Requests.cshtml
@model IEnumerable<PandaApp.Models.Request>
@{
    ViewBag.Title = "Requests";
}

<!-- Search-->
<div class="row text-center">
    @using (Html.BeginForm("SearchResult", "Subtitle"))
    {
        <input type="text" class="form-control" id="input" name="title" size="21" maxlength="120" placeholder="Request search">
        <select class="form-control" id="select" name="language">
            <option value="all" selected>Language</option>
            <option value="icelandic">Icelandic</option>
            <option value="english">English</option>
            <option value="danish">Danish</option>
            <option value="spanish">Spanish</option>
            <option value="swedish">Swedish</option>
            <option value="klingon">Klingon</option>
            <option value="hungarian">Hungarian</option>
        </select>
        <input type="submit" class="btn btn" value="Search">
    }
</div>
<!-- search end-->

<hr />
<div class="row">
    <div class="col-md-7 col-md-offset-2">
        <h4>View Requests</h4>
        <table class="table-striped" width="747">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Language</th>
                    <th>Author</th>
                    <th>Upvotes</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <!-- So the title links to its profile -->
                            @Html.ActionLink(item.Title, "Details", "Request",new { id = item.ID }, null)
                        </td>
                        <td>
                            @item.Language
                        </td>
                        <td>
                            @item.Author
                        </td>
                        <td>
                            @item.Upvotes
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


@Html.ActionLink("Create Request", "Create", null, new { @class = "btn btn-default" })